main: me.miunapa.paserverfeature.PAServerFeature
name: PAServerFeature
version: 0.8.0dev
api-version: 1.15
#depend: [NBTAPI]

commands:
  suicide:
    description: 自殺
    usage: /suicide
    permission: paserverfeature.suicide
  hat:
    description: 戴帽子
    usage: /hat
    permission: paserverfeature.hat
  getip:
    description: 取得玩家IP(必須在線上)
    usage: /getip
    permission: paserverfeature.getip
  rule:
    description: 伺服器規定
    usage: /rule
    permission: paserverfeature.rule
  rules:
    description: 伺服器規定
    usage: /rules
    permission: paserverfeature.rule
  signature:
    description: 地圖複製
    usage: /signature
    permission: paserverfeature.signature
  pvp:
    description: pvp指令
    usage: /pvp
    permission: paserverfeature.pvp
  lc:
    description: 更改鎖箱子指令
    usage: /lc
    permission: paserverfeature.lc
permissions:
  paserverfeature.hat:
    default: true
  paserverfeature.getip:
    default: op
  paserverfeature.suicide:
    default: true
  paserverfeature.bypasslimit:
    default: op
  paserverfeature.rule:
    default: true
  paserverfeature.signature:
    default: true
  paserverfeature.signatureforce:
    default: op
  paserverfeature.pvp:
    default: true
  paserverfeature.pvpbypass:
    default: op
  paserverfeature.lc:
    default: op